// ─── Canonical error codes ────────────────────────────────────────────────────
// These are the machine-readable codes returned in ApiErrorResponse.error.code

export const ErrorCode = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Resource
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // OTP
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_ALREADY_USED: "OTP_ALREADY_USED",
  OTP_SEND_FAILED: "OTP_SEND_FAILED",

  // Onboarding
  ONBOARDING_INCOMPLETE: "ONBOARDING_INCOMPLETE",
  ONBOARDING_STEP_MISSING: "ONBOARDING_STEP_MISSING",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
